image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [610.7274 ,   0.     , 337.78616,
           0.     , 612.23355, 256.44964,
           0.     ,   0.     ,   1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.030309, 0.156561, 0.003321, 0.000032, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [633.87091,   0.     , 336.55067,   0.     ,
           0.     , 637.25397, 257.14029,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
